config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: "users/sessions" }
  root to: 'pages#home'
  # get 'about', to: 'pages#about' # Revisar esta ruta de about
  get 'overview', to: 'publishings#overview'
  get 'mypublishings', to: 'publishings#mypublishings'
  get 'insight', to: 'publishings#insight'
  get 'update_publishings', to:'publishings#update_publishings'
  resources :publishings
  resources :channels, only: [:index, :show]
  get 'last_day', to: 'channels#last_day'
  get 'last_week', to: 'channels#last_week'
  get 'last_month', to: 'channels#last_month'
  get 'last_year', to: 'channels#last_year'
  

  get '/youtube_sessions', to: 'youtube_sessions#new'
  get '/youtube_sessions/callback', to: 'youtube_sessions#callback'
end

app/models/publishing.rb
class Publishing < ApplicationRecord
  has_one_attached :video
  belongs_to :user
  belongs_to :channel
  validates  :title, :status, presence: true
  include PgSearch::Model
  pg_search_scope :search_by_all_publishing_metrics_and_properties,
    against: [ :title, :description, :status, :likes, :views, :shares, :dislikes, :comments, :impressions, :avg_watch_sec, :percent_watch, :scheduled_at, :published_at ],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }

end

app/controllers/publishings_controller.rb
class PublishingsController < ApplicationController
  before_action :set_publishing, only: [:show, :edit, :update, :destroy, :myvideo]
  def index
    @publishings = current_user.publishings
  end
  def show
    # Aca seria solo set_publishing
  end
  def new
    @publishing = Publishing.new
  end
  def edit
  end

  def create
    @publishing = Publishing.new(publishing_params)
    @publishing.user = current_user
    @publishing.channel = current_user.channels.first
    if @publishing.save
      redirect_to publishings_path(@publishing)
    else
      render :new
    end
  end

  def update
    if @publishing.update(publishing_params)
      redirect_to publishing_path(@publishing)
    else
      render :edit
    end
  end

  def mypublishings
    @publishings = Publishing.where(user: current_user)
    @revenue_count = 0
    @views_count = 0
    @shares_count = 0
    channels = Channel.where(user: current_user)
    @subscibers_count = 0
    channels.each do |channel|
      @subscibers_count += channel.subscibers
      publishings = channel.publishings
      publishings.each do |publishing|
        if publishing.revenue != nil
        @revenue_count += publishing.revenue
        end
        if publishing.views != nil
         @views_count += publishing.views
       end
       if publishing.shares != nil
         @shares_count += publishing.shares
       end
      end
    end
  end

  def insight
  end

  def destroy
    if @publishing.destroy
      redirect_to publishings_path(@publishing)
    else
      render :index
    end
  end

  def update_publishings # Boton
    @data = FetchYoutubeAnalytics.call(current_user.youtube_sessions.last) # video_id: view , likes....
    @videos = FetchYoutubeVideos.call(current_user.youtube_sessions.last) # Published videos in YT

      @videos.each do |video_hash|
        publishing = current_user.publishings.find_or_initialize_by(youtube_video_id: video_hash[:id])
        # publishing = Publishing.find_or_initialize_by(youtube_video_id: video_hash[:id])
        if publishing.new_record? # Si es nil ===> tengo que crearlo
          publishing.title = video_hash[:title]
          publishing.description = video_hash[:description]
          publishing.thumbnail = video_hash[:thumbnail]
          publishing.status = "Published on Youtube"
          publishing.published_at = video_hash[:published_at]
          publishing.user = current_user
          # crear el channel
          # channel = Channel.find_or_initialize_by(youtube_channel_id: video_hash[:channel_id]) # A menos que sea un vide de un channel que ya existe, quiero crearlo
          channel = current_user.channels.find_or_initialize_by(youtube_channel_id: video_hash[:channel_id]) # A menos que sea un vide de un channel que ya existe, quiero crearlo
          if channel.new_record? # Si es nil ===> tengo que crearlo
            channel.name = video_hash[:channel_name]
            channel.subscibers = rand(500...1000)
            channel.user = current_user
            channel.save!
          end
          publishing.channel = channel
        end
        # Tanto SI existe como si NO existe, quiero actualizar las 8 metricas y guardarlo
         if @data.key?(video_hash[:id])  # CHECK POR QUE A VECES NO TRAE LA DATA RECIENTE, de videos recien publicados (evito que se rompa la vista)
          publishing.likes = @data[video_hash[:id]][:likes] + rand(1000...5000)
          publishing.views = @data[video_hash[:id]][:views] + rand(1000...10000)
          publishing.comments = @data[video_hash[:id]][:comments] + rand(1000...5000)
          publishing.shares = @data[video_hash[:id]][:shares] + rand(1000...5000)
          publishing.dislikes = @data[video_hash[:id]][:dislikes] + rand(5...15)
          publishing.avg_watch_sec = @data[video_hash[:id]][:avg_watch_sec]
          publishing.percent_watch = @data[video_hash[:id]][:percent_watch]
          publishing.impressions = @data[video_hash[:id]][:impressions] + rand(1000...5000)
          publishing.revenue = rand(1000...3000)
         else
          # Fake data
          publishing.likes =  rand(1000...6000)
          publishing.views =  rand(1000...11000)
          publishing.comments =  rand(1000...7000)
          publishing.shares =  rand(1000...5000)
          publishing.dislikes = rand(10...500)
          publishing.avg_watch_sec = rand(10...500)
          publishing.percent_watch = rand(0...100)
          publishing.impressions =  rand(1000...5000)
          publishing.revenue = rand(1000...3000)
         end

        publishing.save! # si la data vino vacia, lo guardo igual para poder tener al menos el video en Overview

      end
      flash[:notice] =  "Videos Up to date!"
      redirect_to overview_path
  end

  def overview
    if current_user.youtube_sessions.last.nil?
        redirect_to youtube_sessions_path
    else
      if params[:query].present?
        @publishings = current_user.publishings.search_by_all_publishing_metrics_and_properties(params[:query])
      else
        @publishings = current_user.publishings
      end
    end
  end


  private

  def set_publishing
    @publishing = Publishing.find(params[:id])
  end

  def publishing_params
    params.require(:publishing).permit(:video, :title, :description, :status, :youtube_video_id, :scheduled_at)
  end
end

app/views/publishings/index.html.erb
<%# <div class="background-image-index"> %>
    <div class="container">
<!--
    <h1 class="text-left  mt-4 h1 custom-font-size"> Pending and Published Posts</h1>
    <h2 class="text-left  display-4 custom-font-size-sub"> You currently have <strong> <%= @publishings.where(status:"Published on Youtube").count%> </strong> published posts and <strong><%= @publishings.where(status:"Pending").count%> </strong>pending posts to published </h2> -->
    <div class="container pushing-aside d-flex justify-content-between pt-2">
      <div>
        <h1 class="text-left  mt-4 h1 custom-font-size"> Pending and Published Posts</h1>
    <h2 class="text-left  display-4 custom-font-size-sub"> You currently have <strong> <%= @publishings.where(status:"Published on Youtube").count%> </strong> published posts and <strong><%= @publishings.where(status:"Pending").count%> </strong>pending posts to be published </h2>
      </div>
      <div>
      <%= link_to "New Post", new_publishing_path, class:"btn btn-warning rounded-pill "%>
    </div>
    </div>
   </div>


<div class=" d-flex flex-column container-fluid align-items-end sticky-left">
    <div class="card sticky-links">
    <div class="card-body">
      <div>
     <a href="#" rel="tooltip" title="Youtube"><i class="fab fa-youtube-square fa-2x"></i></a>
      </div>
      <div>
    <a href="#" rel="tooltip" title="Facebook"><i class="fab fa-facebook fa-2x"></i></a>
      </div>
      <div>
    <a href="#" rel="tooltip" title="Snapchat"><i class="fab fa-snapchat fa-2x"></i></a>
      </div>
      <div>
    <a href="#" rel="tooltip" title="Instagram"><i class="fab fa-instagram fa-2x"></i></a>
      </div>
      <div>
    <a href="#" rel="tooltip" title="Tiktok"><i class="fab fa-tiktok fa-2x"></i></a>
      </div>
       <div>
     <a href="#" rel="tooltip" title="All Platforms"><i class="fas fa-globe-asia fa-2x"></i></a>
      </div>
    </div> <!-- end card-body-->
  </div>
<div class="background-style-index style-extra">
  <div class="card-position">
 <div class="card-product title-card-index justify-content-center text-center">

  <div>
    <h2>Video</h2>
  </div>
   <div class="card-product-infos">
    <h2>Title</h2>
  </div>
  <div class="card-product-infos">
    <h2>Publication date</h2>
  </div>
  <div class="card-product-infos">
    <h2>total Views</h2>
  </div>
   <div class="card-product-infos">
    <h2>Video Average Watch</h2>
  </div>
   <div class="card-product-infos">
    <h2>Status</h2>
  </div>
  </div>
</div>
</div>
 <div class="background-style-index">
  <div class="card-position">
 <% @publishings.each do |publishing| %>
 <%= link_to publishing_path(publishing.id), class:"text-hover" do %>
 <div class="card-product justify-content-center  ">
  <% if publishing.youtube_video_id %>
    <img src="<%= publishing.thumbnail %>" alt="youtube-image" >
  <% else %>
     <%= cl_video_tag publishing.video.key, height: 100, width: 100 %>
  <% end %>
  <div class="card-product-infos">
    <h2><%= publishing.title.first(15) %></h2>
    <p><%= publishing.description.first(15) %></p>
  </div>
  <div class="card-product-infos text-center ">
  <% if publishing.youtube_video_id %>
    <h2><%= publishing.published_at.to_datetime.strftime('%b %d, %Y') %></h2>
  <%else %>
      <h2><%= publishing.scheduled_at.strftime('%b %d, %Y') %></h2>
  <% end %>
  </div>
  <div class="card-product-infos text-center ">
    <h2><%= number_with_delimiter(publishing.views, :delimiter => ',') %></h2>
  </div>
   <div class="card-product-infos text-center">
    <h2><%= publishing.avg_watch_sec %></h2>
  </div>
   <div class="card-product-infos text-center">
    <h2><%= publishing.status %></h2>
  </div>
  </div>
  <% end %>
  <% end %>
</div>
</div>
</div>
<%# </div> %>

app/views/publishings/mypublishings.html.erb
<%# <div class="background-image-index"> %>
<div class= "container">
<h1 id=" my-castles-title-card "> Account Dashboard </h1>
<div class="row">
<div class= "col-4 mypublishings-card rounded">
   <div class="card-my-publishings rounded">
                                <div class="card">
                                    <h6 class="card-header">Channel Analytics</h6>
                                    <div class="card-body">
                                      <div>
                                        <h6 class="card-title">Subscribers</h6>
                                        <p class="card-text"><strong><%= number_with_delimiter(@subscibers_count, :delimiter => ',') %><i class="fas fa-user-friends"></i></strong></p>
                                        <hr class="blue_line mt10 mb10"/>
                                      </div>
                                      <div>
                                        <h6 class="card-title">Summary</h6>
                                        <div class= "d-flex justify-content-between">
                                        <p class="card-text"><strong>views</strong></p>
                                        <p class="card-text"><i class="fas fa-eye eye-for-my"></i><%=number_with_delimiter(@views_count, :delimiter => ',') %></p>
                                        </div>
                                        <div class= "d-flex justify-content-between">
                                         <p class="card-text"><strong>Shares</strong></p>
                                        <p class="card-text"><i class="fas fa-share"></i><%= number_with_delimiter(@shares_count, :delimiter => ',') %></p>
                                        </div>
                                        <hr class="blue_line mt10 mb10"/>
                                      </div>
                                      <div>
                                        <h6 class="card-title">Total Revenue</h6>
                                        <p class="card-text"><strong>$<%= number_with_delimiter(@revenue_count, :delimiter => ',') %></strong></p>
                                        <hr class="blue_line mt10 mb10"/>
                                      </div>
                                          <%= link_to 'Go To Channel Analytics', channels_path, class:"btn btn-warning rounded-pill"%>

                                    </div> <!-- end card-body-->
                                </div> <!-- end card-->
                            </div>
                       </div>
<div class="col-8" >
    <% counter = 0 %>
    <% @publishings.each do |publishing| %>
      <% counter += 1 %>
    <div class="row d-flex my-publishing-video-card">
  <div class="col-9">
   <%= link_to publishing_path(publishing.id) do %>
   <div class="card-product-my d-flex justify-content-center slight-shadow">
    <% if publishing.youtube_video_id %>
      <img src="<%= publishing.thumbnail %>" alt="youtube-image" >
    <% else %>
       <%= cl_video_tag publishing.video.key, height: 100, width: 100 %>
    <% end %>
    <div class="card-product-infos-my">
      <h2><%= publishing.title.first(15) %></h2>
      <p><%= publishing.description.first(15) %></p>
    </div>
    <div class="card-product-infos-my">
      <% if publishing.youtube_video_id %>
        <h2><%= publishing.published_at.to_datetime.strftime('%a %b %Y %H:%M') %></h2>
      <% else %>
        <h2><%= publishing.scheduled_at.strftime('%a %b %Y %H:%M') %></h2>
      <% end %>
    </div>
    <div class="card-product-infos-my">
      <h2><%= publishing.status %></h2>
    </div>
    </div>
    <% end %>
  </div>
     <div class="col-3" >
      <% if publishing.video.attached? %>
            <p><%= link_to  "Delete Post", publishing_path(publishing.id), method: :delete, class: "btn btn-danger rounded-pill" %></p>
      <% end %>
    </div>
  </div>
  <% end %>

</div>
</div>
</div>
<%# </div> %>

app/views/publishings/myvideo.html.erb
<div class="container container-fluid" id="castle-banner" > <%= cl_video_tag publishing.video.key, height: 300, width: 100 %>


  <div class="container margin-top-negative bg-white p-5 rounded">
    <div class="container-fluid p-0" id="castle-banner" > <%= cl_video_tag publishing.video.key, height: 300, width: 100 %> </div>
    <div class="row mb-3">
      <div class="col-md-8">
        <div p-5>
          <h1><strong><%= @publishing.title %></strong></h1>
          <p class="text-justify"><%= @publishing.description %></p>
          <%= link_to "Back to Overview", root_path, class: "btn btn-secondary" %>
        </div>
      </div>
      <div class="col-md-4 d-flex flex-column">
          <div>
            <div class="card p-3 mb-3">
              <h1>data will go here</h1>
              </div>
          </div>
      </div>
    </div>
          <!-- <div class="container" id="map"
          style="width: 100%; height: 600px; border-radius: 15px;"
          data-markers="<%= @markers.to_json %>"
          data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
          </div>
           -->
  </div>
</div>

app/views/publishings/new.html.erb
<ul class="nav nav-tabs nav-justified nav-bordered mb-3">
    <li class="nav-item mt-3 border border-secondary rounded">
        <a href="#home-b2" data-toggle="tab" aria-expanded="false" class="nav-link active">
            <i class="mdi mdi-home-variant d-md-none d-block"></i>
            <span class="d-none d-md-block"> 1. Video Upload </span>
        </a>
    </li>
    <li class="nav-item mt-3 border border-secondary rounded">
        <a href="#profile-b2" data-toggle="tab" aria-expanded="true" class="nav-link">
            <i class="mdi mdi-account-circle d-md-none d-block"></i>
            <span class="d-none d-md-block">2. Assets </span>
        </a>
    </li>
    <li class="nav-item mt-3 border border-secondary rounded">
        <a href="#settings-b2" data-toggle="tab" aria-expanded="false" class="nav-link">
            <i class="mdi mdi-settings-outline d-md-none d-block"></i>
            <span class="d-none d-md-block">3. Scheduling</span>
        </a>
    </li>
</ul>

    <%= simple_form_for(@publishing) do |f| %>
<div class="container tab-content ">
    <div class="tab-pane show active form-login rounded-form " id="home-b2">
      <h4> Video Upload </h4>
     <%= f.input :video, as: :file, label: false, input_html: {class: "upload-input" } %>
    </div>
    <div class="tab-pane form-login rounded-form " id="profile-b2">
      <h4> Details </h4>
      <%= f.input :title, label: "Video Title:" %>
      <%= f.input :description, as: :text, label: "Video Description:" %>
    </div>
    <div class="tab-pane form-login  rounded-form " id="settings-b2">
      <h4> Visibility </h4>
      <%= f.input :scheduled_at, as: :string, input_html: {class: "datepicker"} %>
      <%= f.input :status, s: :text, input_html: { value: f.object.status.presence || 'Pending' } %>
      <%= f.submit class:"btn btn-warning rounded-pill btn-block" %>
    </div>
     <%= link_to "Cancel", "#", class: "btn btn-danger rounded-pill" %>
</div>
<% end %>

app/views/publishings/overview.html.erb
<body class="background-image">


 <div class="container">
 
  <h1 class="text-left  mt-4 h1 custom-font-size"> 👋🏻 Welcome <%= current_user.first_name%>!</h1>
  <h2 class="text-left  display-4 custom-font-size-sub"> You currently have <%= @publishings.count%> post on YouTube <i class=" mb-2 fab fa-youtube  rounded-pill fa-sm text-success"></i></h2>
 
 </div> 
<div class="container d-flex flex-wrap justify-content-between mt-3 margin-custom parent-positioning">
  <%# <%= button_to 'Refresh video info!', update_publishings_path, class: "btn btn-success rounded-pill", method: :get %>
    <div class="search-wrap d-flex align-items-right">
      <%= form_tag overview_path, class:"search", method: :get do %>
        <%= text_field_tag :query,
          params[:query],
          class: "form-control rounded-pill",
          placeholder: "Views | Comments | Likes | Title | Description"
        %>
      <% end %>
      <i class="fas fa-times clear mt-3 text-warning"></i>
      <i class="fas fa-search searchIcon text-warning"></i>
    </div>
    <div rel="tooltip" title="All Platforms">
        <%= button_to update_publishings_path, class:"btn btn-warning rounded-circle", method: :get do %>
            <i class="fas fa-redo"></i>
        <% end %>
    </div>
</div>


<%# <div class=" alert alert-info alert-dismissible ">
</div> %>
  
  <div class="container background-style p-3 d-flex flex-wrap justify-content-around">
    <div class="alert alert-info msg-hide msg d-flex flex-column justify-content-center align-middle p-2" role="alert">
      <p class="m-0 ">Checkout new posts!</p>
      <small>Updated: <%=@publishings.first.updated_at.strftime('%a %b %Y %H:%M') if @publishings.any?  %></small>
    </div>
    
    <%if @publishings.any?%>
      <% @publishings.each do |publishing|%>
        <%unless publishing.youtube_video_id.nil?%>
          <div class="card-trip m-3">
            <iframe class="embed-responsive-item"  src="https://www.youtube.com/embed/<%=publishing.youtube_video_id%>"
            frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
            allowfullscreen></iframe>
            <div class="card-trip-infos">
              <div>
                <h2><%=publishing.title.first(30)%>...</h2>
                <p><%=publishing.description.first(35)%>...</p>
              </div>
            </div>
            <div class="card-trip-infos metrics-info d-flex">
              <div class="d-flex">
                <i class="far fa-thumbs-up mr-1"></i>
                <h2 data-metric= <%=publishing.likes.nil? ? 0 : publishing.likes %>> <%=publishing.likes.nil? ? 0 : publishing.likes %></h2>
              </div>
              <div class="d-flex">
                  <i  class="far fa-eye mr-1"></i></i>
                <h2 data-metric= <%=publishing.views.nil? ? 0 : publishing.views %>> <%=publishing.views.nil? ? 0 : publishing.views %> </h2>
              </div>
              <div class="d-flex">
                  <i  class="far fa-comment mr-1"></i>
                <h2  data-metric= <%=publishing.comments.nil? ? 0 : publishing.comments %>> <%=publishing.views.nil? ? 0 : publishing.views %> </h2>
              </div>
            </div>
          </div>
        <%end %>   
      <% end %>
    <%end%>
  </div>
</body>

app/views/publishings/show.html.erb
<div class="container container-fluid" id="castle-banner" >
<% if @publishing.youtube_video_id %>
    <img src="<%= @publishing.thumbnail %>" alt="youtube-image" >
  <% else %>
     <%= cl_video_tag @publishing.video.key, height: 100, width: 100 %>
  <% end %>

  <div class="container margin-top-negative bg-white p-5 rounded">

    <div class="row mb-3">
      <div class="col-md-8">
        <div p-5>
          <h1><strong><%= @publishing.title %></strong></h1>
          <p class="text-justify"><%= @publishing.description %></p>
          <%= link_to "Back to Overview", root_path, class: "btn btn-secondary" %>
        </div>
      </div>
      <div class="col-md-4 d-flex flex-column">
          <div>
            <div class="card p-3 mb-3">
              <h1>data will go here</h1>
              </div>
          </div>
      </div>
    </div>
          <!-- <div class="container" id="map"
          style="width: 100%; height: 600px; border-radius: 15px;"
          data-markers="<%= @markers.to_json %>"
          data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
          </div>
           -->
  </div>
</div>