config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: "users/sessions" }
  root to: 'pages#home'
  # get 'about', to: 'pages#about' # Revisar esta ruta de about
  get 'overview', to: 'publishings#overview'
  get 'mypublishings', to: 'publishings#mypublishings'
  get 'insight', to: 'publishings#insight'
  get 'update_publishings', to:'publishings#update_publishings'
  resources :publishings
  resources :channels, only: [:index, :show]
  get 'last_day', to: 'channels#last_day'
  get 'last_week', to: 'channels#last_week'
  get 'last_month', to: 'channels#last_month'
  get 'last_year', to: 'channels#last_year'
  

  get '/youtube_sessions', to: 'youtube_sessions#new'
  get '/youtube_sessions/callback', to: 'youtube_sessions#callback'
end

app/views/shared/_flashes.html.erb
<!-- app/views/shared/_flashes.html.erb -->
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <p class="d-flex  align-middle mt-3 text-white"><strong>Media</strong>Partner</p>

  <div class='container d-flex  align-middle mt-3'>
    <p class='text-md-right fs-6 text-secondary'><i class='fas fa-mobile-alt mr-2 text-secondary'></i> +5411 66784532</p>
    <p class='text-md-right fs-6 text-secondary'><i class='far fa-envelope ml-2 text-secondary'></i> 11000</p>
    <p class='text-md-right fs-6 text-secondary'><i class='fas fa-globe-americas ml-2 text-secondary'></i> Argentina</p>
  </div>
  <div class="footer-links">
    <a href="#"><i class="fab fa-github other-icon-footer"></i></a>
    <a href="#"><i class="fab fa-instagram other-icon-footer"></i></a>
    <a href="#"><i class="fab fa-facebook other-icon-footer"></i></a>
    <a href="#"><i class="fab fa-twitter other-icon-footer"></i></a>
    <a href="#"><i class="fab fa-linkedin other-icon-footer"></i></a>
  </div>
  <div class="footer-copyright">

  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="nav-fixed-black shadow">
      <div class="nav-center">
        <!-- nav header -->
        <% if user_signed_in? %>
          <div class="nav-header">
            <div class="navbar-brand">
              <%= link_to root_path do %>
                <%# <h2 id="svg_1" ><strong>Media</strong>Partner</h2> %>
                <%= image_tag "logo-3.png" %>
              <% end %>
            </div>
            <button class="nav-toggle">
              <i class="fas fa-bars"></i>
            </button>
          </div>
        <% else %>
        <div class="nav-header">
            <div class="navbar-brand">
              <%= image_tag "logo-3.png" %>
            </div>

            <button class="nav-toggle">
              <i class="fas fa-bars"></i>
            </button>
          </div>
        <% end %>
        <!-- links -->
        <% if user_signed_in? %>
          <ul class="links">
            <li>
              <%= link_to 'Overview', overview_path, class:"btn btn-flat subrayado"%>
            <li>
            <li>
              <%= link_to 'Publisher', publishings_path, class:"btn btn-flat subrayado"%>
            <li>
            <li>
              <%= link_to 'Insight', last_day_path, class:"btn btn-flat subrayado"%>
            <li>
            <li>
              <%= link_to 'Performance', channels_path, class:"btn btn-flat subrayado"%>
            <li>
            <li>
              <%= link_to 'Logout', destroy_user_session_path, method: :delete, class:"btn btn-flat subrayado"%>
            <li>
            <li>
              <%= link_to mypublishings_path do %>
                  <%= image_tag "https://513543-1630262-raikfcquaxqncofqfm.stackpathdns.com/wp-content/uploads/2020/05/Brad-Mondo-Hairstyle.png", class: "avatar ml-3" %>
                  
              <% end %>

            <li>


          </ul>
        <% else %>
          <ul class="links">
            <li>
              <%= link_to 'Login', new_user_session_path, class:"btn btn-flat subrayado"%>
            </li>
            <li>
              <%= link_to 'Sign Up', new_user_registration_path, class:"btn btn-flat subrayado" %>
            </li>
          </ul>
        <% end %>
      </div>
    </nav>