config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: "users/sessions" }
  root to: 'pages#home'
  # get 'about', to: 'pages#about' # Revisar esta ruta de about
  get 'overview', to: 'publishings#overview'
  get 'mypublishings', to: 'publishings#mypublishings'
  get 'insight', to: 'publishings#insight'
  get 'update_publishings', to:'publishings#update_publishings'
  resources :publishings
  resources :channels, only: [:index, :show]
  get 'last_day', to: 'channels#last_day'
  get 'last_week', to: 'channels#last_week'
  get 'last_month', to: 'channels#last_month'
  get 'last_year', to: 'channels#last_year'
  

  get '/youtube_sessions', to: 'youtube_sessions#new'
  get '/youtube_sessions/callback', to: 'youtube_sessions#callback'
end

app/views/pages/about.html.erb
<h1>About us</h1>

app/views/pages/home.html.erb
<div class="background-image-home">


  |<div class="container-fluid  d-flex flex-wrap align-center justify-content-between p-4">
    <div>
      <%= image_tag "logo-3.png" %>
    </div>
    <%# <h2 id="svg_2" ><strong>Media</strong>Partner</h2> %>
    <% if user_signed_in? %>
        <%= link_to 'Logout', destroy_user_session_path, method: :delete, class:"btn btn-primary rounded-pill btn-md m-0"%>
    <% else %>
      <div>
        <%= link_to 'Login', new_user_session_path, class:"btn btn-primary rounded-pill"%>
        <%= link_to 'Sign Up', new_user_registration_path, class:"btn btn-primary rounded-pill" %>
      </div>
    <% end %>
  </div>

  <div class="container-fluid margin-container p-5 ">
      <div class="row text-left justify-content-between p-0 m-0">
        <div class="col-5 align-self-center p-0 m-0 text-home text-white ">
          <h2>
            A single tool to aquire audience, track your platforms, reduce expenses and increase revenue.
          </h2>
          <p class="pt-3">
          Gain control of your digital foot print with <strong>Media</strong>Partner.
          </p>
          <% if user_signed_in? %>
            <div class="d-flex justify-content-left">
              <%= link_to 'Overview', overview_path, class:"btn btn-primary rounded-pill btn-md"%>
              <%= link_to 'Youtube account', youtube_sessions_path, class:"btn btn-success rounded-pill btn-md"%>
            </div>
          <% else %>
            <%= link_to 'Lets Start!', new_user_registration_path, class:"btn btn-primary rounded-pill" %>
          <% end %>
        </div>
        <div class="col-7 text-right p-0 m-0">
          <%= image_tag("startup.svg", height:400, width:520, class:"graphics-img") %>
        </div>
      </div>
    </div>

    <%# <div class="container-fluid grad">
    <div class="containter d-flex justify-content-center p-5">
          <h2>We support every social media you can wish for</h2>
      </div>
      <div class="containter d-flex justify-content-center">
          <%= image_tag("social-media.png", height:400, width:520, class:"graphics-img") %>
      <%# </div>  %>
    <%# </div> %>
</div>